<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Herculan.Engine.Host</RootNamespace>
    <AssemblyName>Herculan.Engine.Host</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Herculan.Engine\Herculan.Engine.csproj" />
  </ItemGroup>

</Project>
